### ISSUE TITLE
Quelques commentaires à ajouter

### ISSUE THREAD

**Issue by fandolfatto** [J-Nithujan/NavalBattle_Jegatheeswaran#2]
Quelques commentaires supplémentaires seraient les bienvenus  :
par exemple quand le bateau est coulé, on remplace les X par des 0 dans l'affichage.
Je comprends en lisant le code mais c'est un choix d'implémentation que vous faites et il est plus rapide de l'expliquer.

Ne pas faire référence à des commentaires définis dans d'autres fonctions, mais remettre le commentaire si nécessaire. 
Car imaginons que la fonction référencée soit réécrite, le commentaire disparaîtra et ne sera donc pas visible. Comme rien ne nous rappelle que ce commentaire était utilisé ailleurs, le développeur ne le déplacera pas....

**Comment by J-Nithujan** [comment]
Changé
