### ISSUE TITLE
Fonction gameGridChanges

### ISSUE THREAD

**Issue by fandolfatto** [J-Nithujan/NavalBattle_Jegatheeswaran#4]
Cette fonction ne convient pas : si je l'ai bien comprise, si vous changez la position des bateaux, cette fonction devra être réadaptée. Les valeurs verticales à tester devront être changées, ce qui n'est pas acceptable. Bien que la position des bateaux soit codée en dur ici dans cette version, les fonctions doivent être suffisamment générale pour s'adapter à ces positions, quelles qu'elles soient.

**Comment by J-Nithujan** [comment]
Pas changé pour la v0.1
